website/views.py
from flask import Blueprint,render_template,url_for,redirect,request,flash,session
from .utilities import database,loginrequired
from random import choice

db = database.Database()


view = Blueprint("view",__name__)



@view.route("/")
@loginrequired.login_required
def index():
    return render_template("index.html",subjects=db.get_subjects(session["user_id"]))

@view.route("/subjects/<subject_name>")
@loginrequired.login_required
def viewsubject(subject_name):
    return render_template("subject_questions.html",questions=db.subject_questions(subject_name,user_id=session["user_id"]),subject_name=subject_name)

@view.route("/questions/<question_id>")
@loginrequired.login_required
def question(question_id):
    return render_template("question.html",question=db.get_questions(question_id,session["user_id"]),choices=db.choice_questions(question_id))

@view.route("/question/choices/<question_id>")
@loginrequired.login_required
def viewchoices(question_id):
    return render_template("question_choices.html",question=db.get_questions(question_id,session["user_id"]),choices=db.choice_questions(question_id))


@view.route("/question/create",methods=["POST","GET"])
@loginrequired.login_required
def createquestion():
    if request.method == "POST":
        questiontype = request.form.get("questiontype") 
        subject = request.form.get("subject")
        question = request.form.get("question")
        if not questiontype:
            flash("Please Chose A Question type","warning")
            return redirect(url_for("view.createquestion"))
        if not subject:
            flash("cant create question (please create subject first)","info")
            return redirect(url_for("view.createquestion"))
        if not question:
            flash("Please Enter A Question","info")
            return redirect(url_for("view.createquestion"))
        q1 = db.create_question(question,subject,questiontype,user_id=session["user_id"])
        if questiontype == "MCQ":
            choice1 = request.form.get("choice1")
            choice2 = request.form.get("choice2")
            choice3 = request.form.get("choice3")
            choice4 = request.form.get("choice4")
            correct = request.form.get("correct")
            if not choice1 or not choice2 or not choice3 or not choice4 or not correct:
                flash("Please Dont Leave Input Empty","info")
                return redirect(url_for("view.createquestion"))
            for num,i in enumerate([choice1,choice2,choice3,choice4]):
                if (num+1) == int(correct[-1]):
                    db.create_choice(i,q1.id,1)
                else:
                    db.create_choice(i,q1.id,0)
            flash("Created Question","success")
            return redirect(url_for("view.index"))
        elif questiontype== "TF":
            choice = request.form.get("radio")
            if not choice:
                flash("Please Choose A Choice","info")
                return redirect(url_for("view.createquestion"))
            db.create_choice("True",q1.id,1 if choice == "true" else 0)
            db.create_choice("False",q1.id,1 if choice == "false" else 0)
            flash("Created Question","success")
            return redirect(url_for("view.index"))
        else:
            flash("Wrong Question type","danger")
            return redirect(url_for("view.createquestion"))
    return render_template("createquestion.html",subjects=db.get_subjects(session["user_id"]))

@view.route("/subject/create",methods=["POST","GET"])
@loginrequired.login_required
def create_subject():
    if request.method == "POST":
        subject = request.form.get("name")
        if not subject:
            flash("Please Enter A Subject","info")
            return redirect(url_for("view.create_subject"))
        if db.get_subject(subject,session["user_id"]):
            flash("Subject Already Created","info")
            return redirect(url_for("view.create_subject"))
        db.create_subject(subject,session["user_id"])
        flash("Created Subject","success")
        return redirect(url_for("view.create_subject"))
    return render_template("create_subject.html")

@view.route("/subject/delete",methods=["POST"])
@loginrequired.login_required
def delete_subject():
    subject = request.form.get("subject_name")
    if not subject:
        flash("Something Went Wrong","danger")
        return redirect("/")
    flash("Deleted Subject","info")
    db.delete_subject(subject,session["user_id"])
    return redirect("/")

@view.route("question/delete",methods=["POST"])
@loginrequired.login_required
def delete_question():
    question_id  = request.form.get("question_id")
    if not question_id:
        flash("something went wrong","danger")
        return redirect("/")
    db.delete_question(question_id,session["user_id"])
    flash("deleted question","info")
    return redirect("/")

@view.route("/quiz")
@loginrequired.login_required
def quizview():
    return render_template("quizview.html",subjects=db.get_subjects(session["user_id"]))

@view.route("/quiz/me",methods=["POST"])
@loginrequired.login_required
def quizme():
    if request.method == "POST":
        subject = request.form.get("subject")
        quiztype = request.form.get("quiztype")
        if not subject:
            flash("Please Enter Subject","info")
            return redirect("view.quizme")
        if not quiztype:
            flash("Please Enter QuizType","info")
            return redirect("view.quizme")
        questions = []
        if subject == "all" and quiztype == "all":
            for subjects in db.get_subjects(session["user_id"]):
                questions.extend(db.subject_questions(subjects.name,session["user_id"]))

        elif subject != "all" and quiztype == "all":
            questions = list(db.subject_questions(subject,session["user_id"]))

        elif subject == "all" and quiztype == "random":
            for subjects in db.get_subjects(session["user_id"]):
                questions.extend(db.subject_questions(subjects.name,session["user_id"]))
            questions = [choice(questions) for _ in range(10)] if len(questions) >=10 else questions

        elif subject != "all" and quiztype == "random":
            questions = list(db.subject_questions(subject,session["user_id"]))
            questions = [choice(questions) for _ in range(10)] if len(questions) >=10 else questions
        
        elif subject != "all" and quiztype == "unsolved":
            questions = list(db.get_unsolved_question(subject,session["user_id"]))
        
        elif subject == "all" and quiztype == "unsolved":
            questions = list(db.get_unsolved_questions(session["user_id"]))
        else:
            flash("Something Went Wrong Please Try Again","danger")
            return redirect(url_for("view.quizview"))
        return render_template("quiz.html",questions=questions)
        

website/templates/create_subject.html
{%extends 'layout.html'%} {%block title%}Create Subject {%endblock%} {%block
body%}
<div class="container mt-4">
  <form action="/subject/create" method="post">
    <label class="form-label" for="name">Subject Name:</label>
    <input required class="form-control" type="text" name="name" id="name" />
    <input type="submit" value="Create" class="btn btn-primary mt-2" />
  </form>
</div>
{%endblock%}

website/templates/createquestion.html
{%extends 'layout.html'%} {%block title%} Create Question {%endblock%} {%block
body%}
<h1 class="text-center mt-4">Create Question</h1>
<div class="container">
  <form action="/question/create" method="post">
    <select name="questiontype" class="form-select">
      <option value="TF">True Or False Question</option>
      <option value="MCQ">Multipule Choice Questions</option>
    </select>
    <label for="subject">Subject: </label>
    <select class="form-select" name="subject" id="subject">
      {%for subject in subjects%}
      <option value="{{subject.name}}">{{subject.name}}</option>
      {%endfor%}
    </select>
    <label for="question">question: </label>
    <input class="form-control" type="text" name="question" id="question" />
    <div class="MCQ">
      <input
        class="form-control mt-2"
        type="text"
        name="choice1"
        id="choices"
        placeholder="Choice1: "
      />
      <input
        class="form-control mt-2"
        type="text"
        name="choice2"
        id="choices"
        placeholder="Choice2: "
      />
      <input
        class="form-control mt-2"
        type="text"
        name="choice3"
        id="choices"
        placeholder="Choice3: "
      />
      <input
        class="form-control mt-2"
        type="text"
        name="choice4"
        id="choices"
        placeholder="Choice4: "
      />
      <label for="correct">Correct Answer: </label>

      <select class="form-select" name="correct" id="correct">
        <option value="choice1">Choice1</option>
        <option value="choice2">Choice2</option>
        <option value="choice3">Choice3</option>
        <option value="choice4">Choice4</option>
      </select>
    </div>
    <div class="TF">
      <label for="true">True: </label>
      <input
        class="form-switch"
        type="radio"
        value="true"
        name="radio"
        id="true"
      />
      <label for="false">False: </label>
      <input
        class="form-switch"
        type="radio"
        value="false"
        name="radio"
        id="false"
      />
    </div>
    <input class="btn btn-success mt-3" type="submit" value="Create Question" />
  </form>
</div>
<script src="{{url_for('static',filename='js/createquestion.js')}}"></script>
{%endblock%}

website/templates/index.html
{%extends 'layout.html'%} {%block title%} Home Page {%endblock%} {%block css%}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" />
{%endblock%} {%block body%}

<h1>Hello {{session["username"]}}</h1>
<div class="container mt-3">
  <div class="row g-3">
    {%if subjects%} {%for subject in subjects%}
    <div class="flip-card col-md-4">
      <div class="card flip-card-inner">
        <div
          class="flip-card-front d-flex justify-content-center align-items-center"
        >
          <h1 class="card-title">{{subject.name}}</h1>
        </div>
        <div
          class="flip-card-back d-flex justify-content-center align-items-center"
        >
          <h1>
            <a
              class="link-info face backside card-title"
              href="{{  url_for('view.viewsubject', subject_name=subject.name)}}"
            >
              View Questions
            </a>
          </h1>
        </div>
      </div>
    </div>
    {%endfor%} {%else%}
    <h3>No subjects Found <a href="/subject/create">create</a></h3>
    {%endif%}
  </div>
</div>
<script>
  var cards = document.querySelectorAll(".flip-card");
  cards.forEach((card) => {
    card.style.height = `${card.scrollHeight + 120}px`;
  });
</script>
{%endblock%}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{%block title%} {%endblock%}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    {%block css%} {%endblock%}
  </head>

  <body>
    {%include 'components/navbar.html'%} {%include
    'components/errormessage.html'%} {%block body%} {%endblock%}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/login.html
{%extends 'layout.html'%} {%block title%}Login{%endblock%} {%block body%}
<h1 class="text-center mt-3">Log In</h1>
<form class="container" action="/login" method="post">
  <label class="form-label" for="email">Email:</label>
  <input class="form-control" type="text" name="email" id="email" />
  <label class="form-label" for="username">Username:</label>
  <input class="form-control" type="text" name="username" id="username" />
  <label class="form-label" for="password">Password:</label>
  <input class="form-control" type="password" name="password" id="password" />
  <input class="btn btn-primary mt-3" type="submit" value="Login" />
</form>
<a class="ms-5" href="/signup">Don't have an account?</a>
{%endblock%}

website/templates/question.html
{%extends 'layout.html'%} {%block title%}Question {%endblock%} {%block body%}
<h1>{{question.text}}</h1>
{%for choice in choices%}
<button>{{choice.text}}</button>
{%endfor%} {%endblock%}

website/templates/question_choices.html
{%extends 'layout.html'%} {%block title%} {%endblock%} {%block body%}
<div class="container text-center mt-2">
  <h1>{{question.content}}</h1>
  <ul class="list-unstyled d-flex flex-column">
    {%for choice in choices%} {%if choice.correct == 1%}
    <li correct="1">{{choice.text}}</li>
    {%else%}

    <li>{{choice.text}}</li>
    {%endif%} {%endfor%}
    <div class="answer text-success" style="overflow: hidden">
      <span></span>
    </div>
    <button class="btn btn-primary">Show Answer</button>
  </ul>
</div>
<form action="/question/delete" method="post">
  <input type="hidden" name="question_id" value="{{question.id}}" />
  <input class="btn btn-outline-danger" type="submit" value="Delete" />
</form>

<script src="{{url_for('static',filename='js/question_choices.js')}}"></script>
{%endblock%}

website/templates/quiz.html
{%extends 'layout.html'%} {%block title%} Quiz {%endblock%} {%block body%}
{%block css%} <link rel="stylesheet" href="{{url_for('static',filename='css/quiz.css')}}">{%endblock%}
<div class="main container-fluid">
  {%if questions%}
  {%for question in questions%}
      <div class="w-100 h-100 question fs-1 ">
        <div
          class="question_text d-flex justify-content-center align-items-center"
        >
        <input type="hidden" name="question_id" value="{{question.id}}">
        <h2>{{question.content}}</h2>
        </div>
        {%if question.question_type.name == 'MCQ' %}
        <div class="choices">
          {%for choice in choices(question.id)%}
          {%if choice.correct%}
          <button class="btn btn-outline-info text-black fs-2" choice_id="{{choice.id}}" correct="true">{{choice.text}}</button>
          {%else%}
          <button class="btn btn-outline-info text-black fs-2" choice_id="{{choice.id}}" incorrect="true">{{choice.text}}</button>
          {%endif%}
          {%endfor%}
        </div>
        {%elif question.question_type.name == 'TF'%}
        <div class="choices">
          {%for choice in choices(question.id)%}
          {%if choice.correct == 1 %}
          <button class="btn btn-outline-info text-black fs-2" choice_id="{{choice.id}}" correct="true">{{choice.text}}</button>
          {%else%}
          <button class="btn btn-outline-info text-black fs-2" choice_id="{{choice.id}}" incorrect="true">{{choice.text}}</button>
          {%endif%}
          {%endfor%}
        </div>   
        {%endif%}
      </div>
      {%endfor%}
      {%else%}
      <div class="blank w-100 h-100 d-flex flex-column justify-content-center align-items-center">
        <h1>No Questions Found</h1>
        <a href="/">Go back</a>
      </div>
      {%endif%}

      <div
        class="done w-100 h-100   text-center d-flex flex-column justify-content-center align-items-center"
      >
        <h1>You Have Finished And Your Score Is : <span id="score"></span></h1>
          <a href="/">Go Back</a>
      </div>
    </div>
    <script src="{{url_for('static',filename='js/quiz.js')}}"></script>
</div>
{%endblock%}

website/templates/quizview.html
{%extends 'layout.html'%} {%block title%} Quiz {%endblock%} {%block body%}
<h1>Chose Quiz Type</h1>
<div class="container">
  <form action="/quiz/me" method="post">
    <select class="form-select mt-4" name="subject" id="subject">
      <option value="all">All</option>
      {%for subject in subjects%}
      <option value="{{subject.name}}">{{subject.name}}</option>
      {%endfor%}
    </select>
    <select class="form-select mt-4" name="quiztype" id="quiztype">
      <option value="all">All</option>
      <option value="random">Random</option>
      <option value="unsolved">Unsolved</option>
    </select>
    <input class="btn btn-primary mt-4" type="submit" value="Start Quiz" />
  </form>
</div>

{%endblock%}

website/templates/signup.html
{%extends 'layout.html'%} {%block title%}SIGN UP{%endblock%} {%block body%}
<h1 class="text-center mt-3">Sign up</h1>
<form class="container" action="/signup" method="post">
  <label class="form-label" for="email">Email:</label>
  <input class="form-control" type="text" name="email" id="email" />
  <label class="form-label" for="username">Username:</label>
  <input class="form-control" type="text" name="username" id="username" />
  <label class="form-label" for="password">Password:</label>
  <input class="form-control" type="password" name="password" id="password" />
  <label class="form-label" for="passwordconfirm">Confirm password:</label>
  <input
    class="form-control"
    type="password"
    name="confirmpassword"
    id="passwordconfirm"
  />
  <input class="btn btn-primary mt-3" type="submit" value="Sign up" />
</form>
<a class="ms-5" href="/login">Already Have An Account?</a>
{%endblock%}

website/templates/subject_questions.html
{%extends 'layout.html'%} {%block title%} {{subject_name}}{%endblock%} {%block
body%} {% if questions %}
<div class="d-flex justify-content-between align-items-center">
  <div>
    <h1>{{subject_name}} Questions</h1>
  </div>
  <select class="form-select w-25" name="type" id="type">
    <option selected value="all">all</option>
    <option value="unsolved">Unsolved</option>
    <option value="solved">Solved</option>
  </select>
</div>
<div class="container">
  <div class="row g-3">
    {%for question in questions%}
    <div class="card text-center p-4" solved="{{question.Solved}}">
      <h1 class="card-title">{{question.content}}</h1>
      <div class="card-link">
        <a href="/question/choices/{{question.id}}">View Question</a>
      </div>
    </div>
    {%endfor%}
  </div>
</div>
{%else%}
<h1>Sorrry No Questions Found For {{subject_name}}</h1>
{%endif%}
<form action="{{url_for('view.delete_subject')}}" method="post">
  <input type="hidden" name="subject_name" value="{{subject_name}}" />
  <input
    class="btn btn-outline-danger mt-3"
    type="submit"
    value="Delete Subject"
  />
</form>
<script src="{{url_for('static',filename='js/subject_questions.js')}}"></script>

{%endblock%}